export const avatarInfo = {
  first_name: 'Aang',
  last_name: 'Avatar',
  full_name: 'Avatar Aang',
  subtitle: 'Last Airbender',
  personal_url: 'avataraang.com',
  street_name: '101 Avatar St.',
  apt_no: 'A-123',
  city: 'Southern Air Temple',
  state: 'Hankao',
  zip_code: '12345',
  phone_no: '+1-234-567-8901',
  linkedin_url: 'avataraang.com/linkedin',
  github_url: 'avataraang.com/github',
  email_address: 'avataraang@atla.com',
  objective:
    'To obtain an entry-level software engineering/development position that will challenge me and allow me to utilize my past experiences and skills to mutually benefit both myself and my employer while allowing for future growth and advancement.',
  university: 'Southern Air Temple University',
  university_location: 'Tianjin, Southern Rock',
  university_start_day: 'Feb 2005',
  university_end_day: 'July 2008',
  major: 'Masters in Element Bending',
  university_gpa: '4.0',
  highschool: 'Air Temple Public High School',
  highschool_location: 'Tianjin, Southern Rock',
  highschool_gpa: '3.5',
  sample_courses_description: 'Airbending 101, Waterbending 101, Firebending 101, Earthbending 101, Energybending 101',
  relevant_course_name_1: 'Airbending 101',
  relevant_course_name_2: 'Waterbending 202',
  relevant_course_name_3: 'Earthbending 303',
  relevant_course_name_4: 'Firebending 404',
  work_name_1: 'United Rep. of Nations',
  work_url_1: 'atla.com/urn',
  work_location_1: 'Republic City, R.O.N.',
  work_start_day_1: 'Apr 2034',
  work_end_day_1: 'Present',
  work_role_1: 'Co-Founder',
  work_bullet_1_1: 'Created a society where benders and nonbenders from all four nations could live together in peace.',
  work_bullet_1_2: 'Eased tensions between colonies to prevent war and maintain peace.',
  work_bullet_1_3: 'Temporarily resolved the anti-bending revolution.',
  work_bullet_1_4: 'Sed ut unde omnis iste natus error laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto',
  work_name_2: 'Avatar',
  work_url_2: 'avataraang.com',
  work_location_2: 'Every City, The World',
  work_start_day_2: 'Jun 1905',
  work_end_day_2: 'Present',
  work_role_2: 'Master of all 4 Elements',
  work_bullet_2_1: 'Ended the 100 year war by defeating Fire Lord Ozai and taking his bending abilities away.',
  work_bullet_2_2: 'Re-introduced energy bending to the avatar life cycle.',
  work_bullet_2_3: 'Reduced corruption around the world while travelling.',
  work_bullet_2_4: 'Sed ut unde omnis iste natus error laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto',
  work_name_3: "Aang's School",
  work_url_3: 'avataraang.com/learn',
  work_location_3: 'Republic City, R.O.N.',
  work_start_day_3: 'Jun 2022',
  work_end_day_3: 'Present',
  work_role_3: 'Airbending and Nomad Culture Teacher',
  work_bullet_3_1: 'Revived the Air nomads by passing on the culture and abilities.',
  work_bullet_3_2: "Taught anyone willing to learn about a Monk's way of life.",
  work_bullet_3_3: 'Re-populated all the deserted and barren air temples by making them habitable.',
  work_bullet_3_4: 'Sed ut unde omnis iste natus error laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto',
  project_title_1: 'Firebending',
  project_url_1: 'avataraang.com/fire',
  project_start_day_1: 'Feb 2008',
  project_end_day_1: 'May 2008',
  project_role_1: 'Student',
  project_brief_description_1: '',
  project_long_description_1: '',
  project_bullet_1_1: 'Learned and mastered firebending over the course of 3 months from Zuko.',
  project_bullet_1_2: 'Introduced the concept of dancing and freedom to firebending students.',
  project_bullet_1_3: 'Travelled throughout the Earth Kingdom and learned all unique cultures.',
  project_title_2: 'Earthbending',
  project_url_2: 'avataraang.com/earth',
  project_start_day_2: 'Jan 2008',
  project_end_day_2: 'Jul 2006',
  project_role_2: 'Student',
  project_brief_description_2: '',
  project_long_description_2: '',
  project_bullet_2_1: 'Learned and mastered earthbending over the course of 18 months from Toph.',
  project_bullet_2_2: 'Freed Ba Sing Se from the dictatorship under Long Feng.',
  project_bullet_2_3: 'Travelled throughout the Earth Kingdom and learned all unique cultures.',
  project_title_3: 'Waterbending',
  project_url_3: 'avataraang.com/water',
  project_start_day_3: 'May 2005',
  project_end_day_3: 'May 2006',
  project_role_3: 'Student',
  project_brief_description_3: '',
  project_long_description_3: '',
  project_bullet_3_1: 'Learned and mastered earthbending over the course of 18 months from Katara.',
  project_bullet_3_2: 'Met leaders and warriors around the world forming friendships and alliances.',
  project_bullet_3_3: 'Travelled from the South Pole to the North Pole observing how the world had changed.',
  activity_1_title: 'United Council',
  activity_1_url: 'atla.com/unc',
  activity_1_location: 'Republic City, R.O.N.',
  activity_1_start_day: 'Aug 2036',
  activity_1_end_day: 'Present',
  activity_1_role: 'Councilman',
  activity_1_brief_description: 'Councilman',
  activity_1_long_description: '',
  activity_1_bullet_1: 'Represented myself at the council of five nations as the Avatar.',
  activity_1_bullet_2: 'Made descisions regarding Republic city for public welfare and benefit.',
  activity_1_bullet_3: 'Significantly reduced amount of corruption by ruling on individuals along with the court.',
  activity_2_title: 'Koi Riding Club',
  activity_2_url: '',
  activity_2_location: 'Kyoshi Islands, Kyoshi',
  activity_2_start_day: 'Jan 1905',
  activity_2_end_day: 'Present',
  activity_2_role: 'Founder',
  activity_2_brief_description: 'Founder',
  activity_2_long_description: '',
  activity_2_bullet_1: 'Frequently travelled to Kyoshi island to ride the Elephant Koi as a recreational sport.',
  activity_2_bullet_2: 'Set the record for longest time on a Elephant Koi by 32 minutes.',
  activity_2_bullet_3: 'Mastered the art of riding koi fishes around the world.',
  activity_3_title: 'Order of the White Lotus',
  activity_3_url: '',
  activity_3_location: 'Ba Sing Se, Earth Kingdom',
  activity_3_start_day: 'Jan 1905',
  activity_3_end_day: 'Present',
  activity_3_role: 'Member',
  activity_3_brief_description: 'Member of the club.',
  activity_3_long_description: '',
  activity_3_bullet_1: 'Joined the secret society at the age of 14.',
  activity_3_bullet_2: 'Kept the powers of all nations in check.',
  activity_3_bullet_3: 'Spread and shared secret knowledge to the next generation.',
  programming_language_1: 'English',
  programming_language_2: 'Chinese',
  programming_language_3: 'Arabic',
  programming_language_4: 'French',
  programming_language_5: 'Hindi',
  programming_language_6: 'Portuguese',
  programming_language_7: 'Italian',
  programming_language_8: 'Spanish',
  programming_language_9: 'Thai',
  technical_skill_1: 'Fire-bending',
  technical_skill_2: 'Earth-bending',
  technical_skill_3: 'Air-bending',
  technical_skill_4: 'Water-bending',
  technical_skill_5: 'Energy-bending',
  technical_skill_6: 'Speed',
  technical_skill_7: 'Agility',
  technical_skill_8: 'Nimbleness',
  technical_skill_9: 'Power',
  soft_skill_1: 'Patience',
  soft_skill_2: 'Calmness',
  soft_skill_3: 'Diplomaccy',
  soft_skill_4: 'Fun-loving',
  soft_skill_5: 'Adventurous',
  soft_skill_6: 'Decisiveness',
  soft_skill_7: 'Bravery',
  soft_skill_8: 'Confidence',
  soft_skill_9: 'Hardwork',
  award_1_title: 'NOBEL PEACE PRIZE',
  award_1_description: 'Awarded for peace promotions',
  award_1_day: 'Aug 2026',
  award_2_title: 'AVATAR SCHOLAR AWARD',
  award_2_description: 'Received free education being the Avatar',
  award_2_day: 'Jun 1905',
  award_3_title: 'AWARD TITLE 3',
  award_3_description: 'AWARD DESCRIPTION 3',
  award_3_day: 'MMM YYYY',
  award_4_title: 'AWARD TITLE 4',
  award_4_description: 'AWARD DESCRIPTION 4',
  award_4_day: 'MMM YYYY',
  certifications_description: 'Air Temple Monk Certification',
  technical_skills_description: 'Firebending, Earthbending, Waterbending, Airbending, Energybending, Speed, Agility',
  spoken_languages_description: 'English, Chinese, Arabic, French, Hindi, Spanish'
}
export const placeholderInfo = {
  first_name: 'FNAME',
  last_name: 'LNAME',
  full_name: 'FNAME LNAME',
  subtitle: 'SUB TITLE',
  personal_url: 'myportfolio.com',
  street_name: '101 Resume St.',
  apt_no: 'A-202',
  city: 'City Name',
  state: 'State Name',
  zip_code: '12345',
  phone_no: '+1-234-567-8901',
  linkedin_url: 'linkedin.com/in/username/',
  github_url: 'github.com/username/',
  email_address: 'username@gmail.com',

  objective:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar mattis nunc sed blandit libero volutpat. Nec dui nunc mattis enim.',
  
  university: 'Example Sample University',
  university_location: 'City name, State name',
  university_start_day: 'MMM YYYY',
  university_end_day: 'MMM YYYY',
  major: 'Major in Subject One, Minor in Subject Two',
  university_gpa: 'X.X',
  highschool: 'Example High School',
  highschool_location: 'City name, State name',
  highschool_gpa: 'X.X',
  sample_courses_description: 'Course One, Course Two, Course Three, Course Four',

  work_name_1: 'Company Name One',
  work_url_1: 'companyone.com',
  work_location_1: 'City name, State name',
  work_start_day_1: 'MMM YYYY',
  work_end_day_1: 'MMM YYYY',
  work_role_1: 'Work Role Three',
  work_bullet_1_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_bullet_1_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_bullet_1_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_bullet_1_4: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_name_2: 'Company Name Two',
  work_url_2: 'companytwo.com',
  work_location_2: 'City name, State name',
  work_start_day_2: 'MMM YYYY',
  work_end_day_2: 'MMM YYYY',
  work_role_2: 'Work Role Three',
  work_bullet_2_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_bullet_2_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_bullet_2_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_bullet_2_4: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_name_3: "Company Name Three",
  work_url_3: 'companythree.com',
  work_location_3: 'City name, State name',
  work_start_day_3: 'MMM YYYY',
  work_end_day_3: 'MMM YYYY',
  work_role_3: 'Work Role Three',
  work_bullet_3_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_bullet_3_2: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.",
  work_bullet_3_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  work_bullet_3_4: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  
  project_title_1: 'Project Name One',
  project_url_1: 'projectone.com',
  project_start_day_1: 'MMM YYYY',
  project_end_day_1: 'MMM YYYY',
  project_role_1: 'Project Role 1',
  project_brief_description_1: 'Lorem ipsum dolor sit amet consectetur',
  project_long_description_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar mattis nunc sed blandit libero volutpat. Nec dui nunc mattis enim. ',
  project_bullet_1_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  project_bullet_1_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  project_bullet_1_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  project_title_2: 'Project Name One',
  project_url_2: 'projecttwo.com',
  project_start_day_2: 'MMM YYYY',
  project_end_day_2: 'MMM YYYY',
  project_role_2: 'Project Role 2',
  project_brief_description_2: 'Lorem ipsum dolor sit amet consectetur',
  project_long_description_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar mattis nunc sed blandit libero volutpat. Nec dui nunc mattis enim. ',
  project_bullet_2_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  project_bullet_2_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  project_bullet_2_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  project_title_3: 'Project Name One',
  project_url_3: 'projectthree.com',
  project_start_day_3: 'MMM YYYY',
  project_end_day_3: 'MMM YYYY',
  project_role_3: 'Project Role 3',
  project_brief_description_3: 'Lorem ipsum dolor sit amet consectetur',
  project_long_description_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar mattis nunc sed blandit libero volutpat. Nec dui nunc mattis enim. ',
  project_bullet_3_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  project_bullet_3_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  project_bullet_3_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  
  activity_1_title: 'Organization Name One',
  activity_1_url: 'orgone.com',
  activity_1_location: 'City name, State name',
  activity_1_start_day: 'MMM YYYY',
  activity_1_end_day: 'MMM YYYY',
  activity_1_role: 'Member',
  activity_1_brief_description: 'Lorem ipsum dolor sit amet consectetur',
  activity_1_long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar mattis nunc sed blandit libero volutpat. Nec dui nunc mattis enim. ',
  activity_1_bullet_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  activity_1_bullet_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  activity_1_bullet_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  activity_2_title: 'Organization Name Two',
  activity_2_url: 'orgtwo.com',
  activity_2_location: 'City name, State name',
  activity_2_start_day: 'MMM YYYY',
  activity_2_end_day: 'MMM YYYY',
  activity_2_role: 'Member',
  activity_2_brief_description: 'Lorem ipsum dolor sit amet consectetur',
  activity_2_long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar mattis nunc sed blandit libero volutpat. Nec dui nunc mattis enim. ',
  activity_2_bullet_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  activity_2_bullet_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  activity_2_bullet_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  activity_3_title: 'Organization Name Three',
  activity_3_url: 'orgthree.com',
  activity_3_location: 'City name, State name',
  activity_3_start_day: 'MMM YYYY',
  activity_3_end_day: 'MMM YYYY',
  activity_3_role: 'Member',
  activity_3_brief_description: 'Lorem ipsum dolor sit amet consectetur',
  activity_3_long_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar mattis nunc sed blandit libero volutpat. Nec dui nunc mattis enim. ',
  activity_3_bullet_1: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  activity_3_bullet_2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  activity_3_bullet_3: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
  
  programming_language_1: 'English',
  programming_language_2: 'Chinese',
  programming_language_3: 'Arabic',
  programming_language_4: 'French',
  programming_language_5: 'Hindi',
  programming_language_6: 'Portuguese',
  programming_language_7: 'Italian',
  programming_language_8: 'Spanish',
  programming_language_9: 'Thai',
  technical_skill_1: 'Fire-bending',
  technical_skill_2: 'Earth-bending',
  technical_skill_3: 'Air-bending',
  technical_skill_4: 'Water-bending',
  technical_skill_5: 'Energy-bending',
  technical_skill_6: 'Speed',
  technical_skill_7: 'Agility',
  technical_skill_8: 'Nimbleness',
  technical_skill_9: 'Power',
  soft_skill_1: 'Patience',
  soft_skill_2: 'Calmness',
  soft_skill_3: 'Diplomaccy',
  soft_skill_4: 'Fun-loving',
  soft_skill_5: 'Adventurous',
  soft_skill_6: 'Decisiveness',
  soft_skill_7: 'Bravery',
  soft_skill_8: 'Confidence',
  soft_skill_9: 'Hardwork',
  
  award_1_title: 'AWARD TITLE ONE',
  award_1_description: 'Description for award one',
  award_1_day: 'MMM YYYY',
  award_2_title: 'AWARD TITLE TWO',
  award_2_description: 'Description for award two',
  award_2_day: 'MMM YYYY',
  award_3_title: 'AWARD TITLE THREE',
  award_3_description: 'Description for award three',
  award_3_day: 'MMM YYYY',
  award_4_title: 'AWARD TITLE FOUR',
  award_4_description: 'Description for award four',
  award_4_day: 'MMM YYYY',
  
  certifications_description: 'Certification One, Certification 2, Certification 3',
  technical_skills_description: 'Tech Skill One, Tech Skill Two, Tech Skill 3, Tech Skill 4',
  spoken_languages_description: 'Spoken Language 1, Spoken Language 2',
  hobbies_description: 'Hobby One, Hobby Two, Hobby Three, Hobby Four, Hobby Five',
}

export const defaultTemplateAbout = {
  designer: "tatiaris",
  next: '1',
  prev: '1',
  tags: [],
  fields: ["full_name","subtitle","city","state","phone_no","email_address","university_start_day","university_end_day","university","university_location","major","sample_courses_description","work_role_1","work_name_1","work_location_1","work_url_1","work_start_day_1","work_end_day_1","work_bullet_1_1","work_bullet_1_2","work_bullet_1_3","work_role_2","work_name_2","work_location_2","work_url_2","work_start_day_2","work_end_day_2","work_bullet_2_1","work_bullet_2_2","work_bullet_2_3","work_role_3","work_name_3","work_location_3","work_url_3","work_start_day_3","work_end_day_3","work_bullet_3_1","work_bullet_3_2","work_bullet_3_3","project_role_1","project_title_1","project_brief_description_1","project_url_1","project_start_day_1","project_end_day_1","project_bullet_1_1","project_bullet_1_2","project_bullet_1_3","project_role_2","project_title_2","project_brief_description_2","project_url_2","project_start_day_2","project_end_day_2","project_bullet_2_1","project_bullet_2_2","project_bullet_2_3","project_role_3","project_title_3","project_brief_description_3","project_url_3","project_start_day_3","project_end_day_3","project_bullet_3_1","project_bullet_3_2","project_bullet_3_3","technical_skills_description","spoken_languages_description","hobbies_description", "personal_url_title", "personal_url", "github_url_title","github_url", "linkedin_url_title","linkedin_url"],
}

export const defaultTemplateDBInfo = {
    "templateId": "1",
    "designer":"tatiaris",
    "likes": 0,
    "downloads": 0,
    "thumbnail":""
}

export const defaultTemplateConfig = {
  pageHeight: '',
  pageWidth: '',
  verticalMargin: '',
  horizontalMargin: '',
  regularFont: 'Roboto',
  regularFontSize: '12pt',
  regularFontWeight: '300',
  boldFontWeight: '500',
  headingFont: 'Roboto',
  headingFontSize: '16pt',
  listConfig: { display: 'list-item', listStyleType: `"\\2014"`, paddingInlineStart: '1ch', marginBottom: '0', lineHeight: '1.5' },
  userInfo: placeholderInfo
}